# Never change this!
version: 2
# Enable to get more information in our server console
debug: false
# Allows us to collect anonymized data about how you use the plugin.
# This helps us to make the right decision in further development.
metrics: true
# Settings for selector
selectorSettings:
  # The character you want to use when entering a path
  pathSeperator: /
  # We prefix the path with the source of the path. Use this if you have directories with equal names in your sources.
  pathSourceAsPrefix: false
# Manage which directories we use for schematic loading
schematicSources:
  # Directories we should search for schematics
  scanPathes:
    # Schematic brush directory
    schematicBrush:
      # path of directory. Seperate folder name with '/'
      path: SchematicBrushReborn/schematics
      # prefix. this is always required. Also when you set pathSourceAsPrefix to false.
      prefix: sbr
    fawe:
      path: FastAsyncWorldEdit/schematics
      prefix: fawe
    worldEdit:
      path: WorldEdit/schematics
      prefix: we
  # Define pathes which we should not scan inside the sources. Use the prefix to define the source.
  # Use a '*' at the end to exlude all schematic in subfolders too.
  excludedPathes:
    - prefix/none
# We will save your presets here
presets: