name: Publish to Nexus

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev*
      - feature/*
      - release/*
      - fix/*

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Test with Gradle
        run: ./gradlew test build
      - name: Publish to eldonexus
        run: ./gradlew publishMavenPublicationToEldoNexusRepository
        env:
          PUBLIC: TRUE
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
